# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('html_name', models.CharField(max_length=32, verbose_name='HTML Name')),
                ('order', models.PositiveIntegerField()),
                ('url_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleImageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpage_core.Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            bases=('webpage_core.content',),
        ),
        migrations.CreateModel(
            name='SimpleText',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpage_core.Content')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('text', tinymce.models.HTMLField()),
            ],
            bases=('webpage_core.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.ManyToManyField(related_name='contents', to='webpage_core.Page'),
        ),
        migrations.CreateModel(
            name='ImageTextContent',
            fields=[
                ('simpleimagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpage_core.SimpleImageContent')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('text', tinymce.models.HTMLField()),
            ],
            bases=('webpage_core.simpleimagecontent',),
        ),
    ]
