# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
