# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_core', '0003_auto_20160220_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
